import express from "express";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import cors from "cors";

dotenv.config();
const app = express();
const allowedOrigins = [
  "http://localhost:5173",
  "https://Netflix-Ai.web.app"
];

app.use(cors({
  origin: function (origin, callback) {
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error("Not allowed by CORS"));
    }
  }
}));

app.use(express.json());


const ai = new GoogleGenAI({
  apiKey: process.env.API_KEY
}); 

const MODEL = "gemini-2.5-flash-lite";
const PORT = process.env.PORT || 5000;

app.get("/", (req, res) => {
  res.status(200).json({ message: "Gemini Proxy Backend is operational." });
});

app.post("/api/gemini", async (req, res) => {
  const { prompt } = req.body; 

  if (!prompt) {
    return res.status(400).json({ error: "Prompt is required in the request body." });
  }

  try {
    const response = await ai.models.generateContent({
      model: MODEL,
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    });

    const text = response.text; 

    if (text) {
      const movies = text.split(",").map((m) => m.trim()).filter(m => m.length > 0);
      res.json({ movies });
    } else {
      res.status(404).json({ movies: [], error: "No content generated by the model" });
    }
  } catch (err) {
    console.error("Gemini API Error:", err.message);
    res.status(500).json({ error: `Internal Server Error: ${err.message}` });
  }
});

app.listen(PORT, () => console.log(`Backend running on http://localhost:${PORT}`));